# Generated by Django 4.2.3 on 2023-07-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('identificacion', models.IntegerField(default=0)),
                ('nombres', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(default=0)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
